MESSAGES = [
    "Your goal is to produce a formal report. You have a fully completed successful applications to the Innovation Norway Grant, entitled: “COMPLETED IN PHASE 1 - SOLINTEGRA AS” and “COMPLETED IN PHASE 1 - ERKE TEKNOLOGI AS” within your knowledge base. You must analyze these applications, understanding and extracting key features that you think made the applications successful, including frequently used phrases, tone, writing style, keywords, and conceptual frameworks as well as recognizing patterns in how applicants present their business models, market analyses, and financial projections. HOWEVER you must not regurgitate any specific information related to the business detailed within the application. The goal of your analysis is to understand what defines a successful application for the Innovation Norway grant in order to impart this wisdom on other businesses that wish to ensure their application to the Innovation Norway Grant is a success. After you complete your analysis please present all of your findings in your report.",
    "Great, now I need you to act as a senior business funding consultant. Your role now is to guide applicants in crafting a compelling funding application for the Innovation Norway Grant, based on your findings. Your explanations and suggestions for the user must be incredibly detailed, providing as much relevant information to the user as possible. I would like you to begin with an initial assessment of the user’s business, they have provided 2 PDFs entitled: “VBAI compiled information” and “VB AI pitchdeck” these files present information regarding their business, you must analyze these PDFs in order to fully understand the user’s business. When assisting the user with an application you must exclusively base your reasoning and responses on the files uploaded to your knowledge base. If that is understood, present your findings in the form of a formal report to the user.",
    "Before we continue you must make sure that you have all the relevant information in order to complete the questions/sections within the application. Generate a numbered list of each questions and evaluate each question based on whether you have enough information from the documents within your knowledge base in order to answer the question, rating each question either Insufficient, sufficient, very sufficient. Insufficient means you require much more information and you are unable to answer the question based on the information you have currently. Insufficient rankings must be accompanied by a bullet-point list stating what further information you require in order to rate this question as Very Sufficient. Sufficient means you are able to answer the question based on the information you have but you have currently but your draft answer could still benefit from having more information. Sufficient rankings must be accompanied by a bullet-point list stating what information you require in order to rate this question as Very Sufficient. Very Sufficient means that you have all the information you require from the documents provided in order to fully answer the question and you require no further information. Very sufficient ratings are very rare. You must be incredibly scrupulous at this stage. It is VITAL that ANY and ALL missing information is stated. Your opinion is that the more information the better, and you always encourage users to add any additional relevant information. If that is all understood, start by analyzing all the documents within your knowledge base and generate the list.If the user's response begins with: 'Heres some additional information:' regenerate the list again, now updated to reflect tha additional information the user has now provided. Do NOT generate the draft answers unless explicity asked to by the user.",
    "I would now like your help to complete the first draft of my application using the information you have extracted from your research during our conversation, question by question, starting with the first question. Please state the character count of the draft answers you produce. Once you have completed the draft of the first question you may ask to move on to the next question or whether the user has any adjustments. Your draft answers must be at least 75% of the character limit for that question. Please start by providing a draft answer to the first question. Your draft answer must be formatted as text. Please provide your response in English. Each time you produce a draft answer, generate an explanation as to why this is a good draft answer, using this opportunity as a teaching moment for the user. Format your explanation as a numbered list.  Please start by providing a draft answer to the first question.",
    "Goodbye!"
]

PHASE_NAMES = [
    "Application Analysis",
    "Business Analysis",
    "Information Sufficiency Analysis",
    "Draft Answer Generation",
    "Conclusion"
]

PITCH_DECK_MESSAGES = [
    "The start-up that I would like you to create a formal report for is called: {company_name}. I will now provide you with information, in the form of documents and/or transcripts, containing the information that I would like you to use during our interaction. Please thoroughly analyze all the documents I have provided so you fully understand every aspect of the start-up, once you have completed your analysis please generate a comprehensive, well formatted and formal business report of the start-up in question, using information extracted from the uploaded information. Your report should provide an overview of the entire company, NOT a slide by slide breakdown.",
    "Great! I would now like you to suggest between 17 to 25 slides that when combined will create the pitchdeck. Please base your suggestion upon what slides you feel would be most relevant and suitable given the nature of the start-up. You must present a list of your suggested slides to the user, for each slide you must state the number of the slide, the title of the slide, a brief description of its contents and a concise explanation of why the user should include this slide within the pitchdeck. After you have presented this information to the user you must ask them to select the slides they would like to be included within the pitchdeck and whether they would like to add any additional slides to choose from.",
    "I select the following slides: '{selected_slides}'. You now must analyze the information uploaded, extracting only information relevant to the start-up stated by the user. You must now use this extracted information to produce a formal information gap analysis report, in which you will rate the information sufficiency for each of the selected slides. For each slide you must rate the information sufficiency from 0 (Meaning you don't have any information that will contribute towards the slide) to 10 (meaning you have all the information you require to write the perfect content for that slide). At the end of this report you will highlight the required information that would be most beneficial to the generation of the pitchdeck and ask the user to provide additional files. You must also generate a comprehensive list of questions that once answered by the user will provide you with all the information you require to be able to rate each slide as 10.",
    "Great. Using all the information extracted from the documents and this conversation I would like you to now produce the entire content for the pitch deck, organized by slide, with each slide containing all the information that should be displayed on the slide. You should also provide an explanation as why its a good idea to include this information within the slide and another bullet point list which identifies and highlights any missing or incomplete content, flagging areas where additional data or clarification would enhance the slide (E.g. timelines, figures, metrics)."
]

PITCH_DECK_PHASE_NAMES = [
    "1. Business Report Generation",
    "2. Slide Suggestion",
    "3. Information Evaluation",
    "4. Draft Slide Generation"
]